config/routes.rb
Streamcongress::Application.routes.draw do

  root :to => 'main#index'
  match 'settings' => 'main#settings', :as => :settings
  match 'chrome' => 'main#chrome', :as => :chrome
  match 'about' => 'main#about', :as => :about
  match 'contact' => 'main#contact', :as => :contact

  match 'auth' => 'sessions#new', :as => :auth
  match 'out' => 'sessions#destroy', :as => :out

  match 'latest' => 'main#latest', :as => :latest
  match 's/:slug' => 'main#publisher', :as => :publisher
  match 'a/:id' => 'main#activity', :as => :activity
  match 'a/:id/comment' => 'main#comment', :as => :comment

  resource :session

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_filter :ensure_signed_in, :only => [:settings, :comment]
  before_filter :user_agent_check, :except => [:chrome]

  def index

  end

  def settings
    if subscriber = params[:subscriber] && !params[:subscriber][:display_name].blank?
      @subscriber.display_name = params[:subscriber][:display_name]
      @subscriber.save!
      redirect_to root_path
    end
  end

  def publisher
    @publisher = Publisher.where(:slug => params[:slug]).first
  end

  def latest
    if params[:since_id] == "0"
      @activities = Activity.any_in(:publisher_ids => params[:following_ids].split(',')).
                             desc(:_id).
                             limit(20)
    else
      @activities = Activity.where(:_id.gt => BSON.ObjectId(params[:since_id])).
                             any_in(:publisher_ids => params[:following_ids].split(',')).
                             desc(:_id).
                             limit(100)
    end
    render :json => @activities
  end

  def activity
    @activity = Activity.find(params[:id])
  end

  def comment
    @activity = Activity.find(params[:id])
    @activity.comments.create(:body => params[:body],
                              :subscriber_id => @subscriber.id,
                              :display_name => @subscriber.display_name)
    @activity.save
    redirect_to :back
  end

  def user_agent_check
    agent = Agent.new request.env["HTTP_USER_AGENT"]
    redirect_to chrome_path if agent.name == :IE
  end

end

app/views/main/about.html.erb
<% content_for :current_page, 'settings' %>
<h2 class="withTip">About</h2>

<p>Stream Congress is a comprehensive news feed that tracks the online activity of Congress in real time. It compiles various streams of updates from members of Congress into a single information stream, which can then be customized by users.</p>

<p>Currently, we track:</p>
<ul style="list-style-type:circle;margin-left:20px;">
  <li>Tweets</li>
  <li>YouTube uploads</li>
  <li>News articles</li>
  <li>House and Senate floor updates</li>
  <li>Bill status and floor votes</li>
  <li>Committee hearing notices</li>
  <li>Whip notices</li>
</ul>

<p>Facebook updates are coming soon.</p>

<p>Stream Congress is a project of the <a href="http://sunlightfoundation.com">Sunlight Foundation</a>.</p>

app/views/main/activity.html.erb
<% content_for :current_page, 'activity' %>

<script type="text/javascript" charset="utf-8">
  var activity = <%= @activity.to_json.html_safe %>;
</script>

app/views/main/chrome.html.erb
<% content_for :current_page, 'settings' %>
<h2 class="withTip">Install Google Chrome Frame</h2>

<p><a href="http://google.com/chromeframe/"><img width="200px" style="border:none;" src="http://www.google.com/images/icons/illustrations/chrome_frame-430.png" /></a><br/></p>

<p>Stream Congress utilizes advanced features, and requires Google Chrome Frame to operate. <a href="http://google.com/chromeframe/">Install it</a> now.</p>

app/views/main/contact.html.erb
<% content_for :current_page, 'settings' %>
<h2 class="withTip">Contact</h2>

<p>Question or problem with the app? Send us an <a href="mailto:streamcongress@sunlightfoundation.com">email</a>.

app/views/main/index.html.erb
<% content_for :current_page, 'home' %>
<h2 id="happeningTitle">Happening Now...</h2>
<article id="geolocationPrompt">
  <div class="articleContent">
    <img src="/images/ajax-loader.gif" class="ajaxLoader"/>
    <h3>Please allow location detection above to identify your members of Congress.</h3>
  </div>
</article>

<!--<article>
  <img src="images/pic1.jpg" />
  <div class="articleContent">
    <a class="date" href="#">9.30.10 18:34:30</a>
    <h3>Sen. Jim Webb was mentioned in Wall Street Journal Blogs: VA Lawmakers Urge Obama to Stop Military Closing –</h3>
    <p>Lawmakers are stepping up a campaign to force the Pentagon to rethink plans to close a Virginia-based military command...</p>
    <ul>
      <li><a href="#">0 comments</a></li>
      <li><a href="#">View Original</a></li>
    </ul>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</article>
<article>
  <img src="http://assets.sunlightfoundation.com/moc/100x125/W000805.jpg" width="59px" />
  <div class="articleContent">
    <a class="date" href="#">9.30.10 12:04:03</a>
    <h3>Sen. Mark Warner tweeted -</h3>
    <p>Great visits, productive conversations this wk in Winchester, Harrisonburg, Staunton VA. Blogs,pics @ www.warner.senate.gov -Staff</p>
    <ul>
      <li><a href="#">0 comments</a></li>
      <li><a href="#">View Original</a></li>
    </ul>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</article>
<article>
  <img src="http://assets.sunlightfoundation.com/moc/100x125/C001078.jpg" width="59px" />
  <div class="articleContent">
    <a class="date" href="#">9.30.10 11:48:45</a>
    <h3>Rep. Gerry Connolly posted a video:</h3>
    <object width="300" height="250"><param name="movie" value="http://www.youtube.com/v/8EqI7qOrKWE?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/8EqI7qOrKWE?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300" height="250"></embed></object><br />
    <p>Connolly calls for hearings to determine rationale behind Secretary Gates defense recommendations</p>
    <ul>
      <li><a href="#">0 comments</a></li>
      <li><a href="#">View Original</a></li>
    </ul>
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
</article>-->

app/views/main/publisher.html.erb
<% content_for :current_page, 'publisher' %>
<div id="vcard">
  <h2>Stream for <%= @publisher.name %></h2>
  <% if @publisher.publisher_type == "member" -%>
  <div id="mainVcard">
    <span class="tel"><%= @publisher.state%>-<%= @publisher.district %></span>
  </div>
  <div id="buttons">
      <% unless @publisher.twitter_id.blank? %>
      <a class="twitter" title="Twitter" href="http://twitter.com/<%= @publisher.twitter_id %>">Twitter</a>
      <% end %>

      <% unless @publisher.youtube_id.blank? -%>
      <a class="youtube" title="YouTube" href="http://youtube.com/<%= @publisher.youtube_id %>">YouTube</a>
      <% end -%>
      <a class="opencongress" title="Open Congress" href="http://www.opencongress.org/person/show/<%= @publisher.govtrack_id %>">Open Congress</a>
  </div>
  <% end -%>
  <div class="clear"></div>
</div>
<script type="text/javascript" charset="utf-8">
  var publisherId = '<%= @publisher.id %>';
  var publisherSlug = '<%= @publisher.slug %>';
</script>

app/views/main/settings.html.erb
<% content_for :current_page, 'settings' %>
<h2 class="withTip">Settings</h2>
<span class="tip">Customize your display name, shown whenever you leave a comment.</span>
<%= form_for(@subscriber, :url => settings_path) do |f| %>
  <ul>
    <li>
      <label>Display Name</label>
      <%= f.text_field :display_name, :class => "full" %>
    </li>
    <li>
      <button class="signupBtn" type="submit">
        <span>Sign Up</span>
      </button>
    </li>
  </ul>
<% end %>