config/routes.rb
Streamcongress::Application.routes.draw do

  root :to => 'main#index'
  match 'settings' => 'main#settings', :as => :settings
  match 'chrome' => 'main#chrome', :as => :chrome
  match 'about' => 'main#about', :as => :about
  match 'contact' => 'main#contact', :as => :contact

  match 'auth' => 'sessions#new', :as => :auth
  match 'out' => 'sessions#destroy', :as => :out

  match 'latest' => 'main#latest', :as => :latest
  match 's/:slug' => 'main#publisher', :as => :publisher
  match 'a/:id' => 'main#activity', :as => :activity
  match 'a/:id/comment' => 'main#comment', :as => :comment

  resource :session

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= csrf_meta_tag %>
  <meta name="description" content="A comprehensive ticker to track online activity coming from Congress in real time." />
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <title>Stream Congress</title>
  <link rel="shortcut icon" href="/favicon.ico" />
  <link rel="stylesheet" href="/stylesheets/main.css" type="text/css" media="screen" />

  <!--[if IE 6]><link rel="stylesheet" href="buggy.css" type="text/css" media="screen" /><![endif]-->
  <!--[if IE 7]><link rel="stylesheet" href="buggy7.css" type="text/css" media="screen" /><![endif]-->
</head>

<body class="home">
  <div id="pageMain">
    <header>
      <h1><a href="/">Stream Congress</a></h1>
      <div id="headerNav">
        <ul>
          <% if signed_in? -%>
          <li>Hi, <%= current_user.display_name %> | <%= link_to "Sign Out", out_path %></li>
          <% else -%>
          <li><%= link_to "Sign In With Google", auth_path %></li>
          <% end -%>
        </ul>
        <div class="clear"></div>
      </div>
    </header>
    <div id="mainContent">
      <div id="ltColumn">
        <div id="congressSessions">
          <dl>
            <% ["House", "Senate"].each do |chamber| -%>
              <% if in_session?(chamber) %>
                <dt class="in"><%= chamber %></dt>
                <dd>In Session</dd>
              <% else %>
                <dt class="out"><%= chamber %></dt>
                <dd>Out of Session</dd>
              <% end %>
            <% end -%>
          </dl>
        </div>
        <div class="module">
          <h3 class="withTip">Currently Following</h3>
          <% if signed_in? -%>
          <span class="tip" id="following_tip">Edit your follow list below.</span>
          <% else -%>
            <span class="tip" id="following_tip">Please allow location detection to auto-follow your elected officials.</span>
          <% end -%>
          <ul id="following"></ul>
        </div>
        <div class="module">
          <h3 class="withTip">Follow More</h3>
          <!--<h4>Groupings</h4>
          <form action="#">
            <div class="scroll">
              <ul>
                <li>
                  <label><input class="checkbox" type="checkbox" name="word" />Senate Floor Updates</label>
                </li>
                <li>
                  <label><input class="checkbox" type="checkbox" name="word" />House Floor Updates</label>
                </li>
                <li>
                  <label><input class="checkbox" type="checkbox" name="word" />Senate Tweets</label>
                </li>
                <li>
                  <label><input class="checkbox" type="checkbox" name="word" />House Tweets</label>
                </li>
              </ul>
            </div>
            <button class="addBtn" type="submit">
              <span>Add</span>
            </button>
          </form>-->
          <span class="tip">Type in the name of a specific legislator</span>
            <input id="memberSearch" type="text" name="name"/>
            <button class="addBtn" id="memberSearch">
              <span>Add</span>
            </button>
        </div>
      </div>
      <div id="rtColumn">
        <div id="rtColumn_content">
          <%= yield %>
        </div>
        <div id="rtColumnFooter"></div>
      </div>
      <div class="clear"></div>

    </div>
  </div>
  <div class="clear"></div>
  <div id="footerWrapper">
    <footer>
      <div id="footerNav">
        <ul>
          <li><a href="/about">About</a></li>
          <li class="last"><a href="/contact">Contact</a></li>
        </ul>
        <div class="clear"></div>
      </div>
      <div id="disclaimer">
        <a class="linkReplacement" id="sf" href="http://www.sunlightfoundation.com">Sunlight Foundation</a>
        <p>Founded in 2006, the Sunlight Foundation is a non-partisan non-profit that uses cutting-edge technology and ideas to make government transparent and accountable. Visit <a href="http://www.sunlightfoundation.com">SunlightFoundation.com</a> to learn more.</p>
      </div>
    </footer>
  </div>
  <script type="text/javascript">

    var currentPage = '<%= yield :current_page %>';
    var signedIn = <%= signed_in? %>;
    var userName = '<%= current_user.display_name if signed_in? %>';
    var sunlightKey = '4eb10599f1c947868810783a5f4fd50a'
    var socketDomain = '<%= Rails.env == "production" ? "streamcongress.com" : "localhost" %>';
    var defaultFollows = <%= default_follows.inspect.html_safe %>;
    var groupIds = defaultFollows;
    var allMembers = <%= all_members.inspect.html_safe %>;
    var allMemberIds = <%= all_member_ids.inspect.html_safe %>;
    var allMemberNames = <%= all_member_names.inspect.html_safe %>;
    var memberNameLookup = <%= member_name_lookup.to_json.html_safe %>;
    var slugLookup = <%= slug_lookup.to_json.html_safe %>;
    var activityQueue = [];
    var queueProcessing = false;

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-1265484-67']);
    _gaq.push(['_setDomainName', 'none']);
    _gaq.push(['_setAllowLinker', true]);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js'></script>
  <script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
  <script src='http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js'></script>
  <script id="activityTemplate" type="text/x-jquery-tmpl">
    <article>
      {{if source_name == "house floor"}}
        <img src="/images/house_profile.jpg" width="59px" />
      {{else source_name == "senate floor"}}
        <img src="/images/senate_profile.jpg" width="59px" />
      {{else}}
        <img src="http://assets.sunlightfoundation.com/moc/100x125/${bioguide_id}.jpg" width="59px" />
      {{/if}}
      <div class="articleContent">
        <div class="date">
            <a href="/a/${_id}">${date}</a>
            <span>${time}</span>
        </div>
        {{if source_name == "twitter"}}
        <h3>${name} tweeted:</h3>
        <p>{{html main_content}}</p>
        {{else source_name == "news"}}
        <h3>${name} was mentioned in &quot;${main_content}&quot;:</h3>
        <p>${secondary_content}</p>
        {{else source_name == "youtube"}}
        <h3>${name} posted a video:</h3>
        <object width="300" height="250"><param name="movie" value="http://www.youtube.com/v/${source_id}?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/${source_id}?fs=1&amp;hl=en_US&amp;rel=0&amp;hd=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="300" height="250"></embed></object><br />
        <p>${secondary_content}</p>
        {{else source_name == "house floor"}}
        <h3>Update from the House Floor</h3>
        <p>${main_content}</p>
        {{else source_name == "senate floor"}}
        <h3>Update from the Senate Floor</h3>
        <p>${main_content}</p>
        {{/if}}
        <ul>
          {{if comments}}
          <li><a href="/a/${_id}">${comments.length} comments</a></li>
          {{else}}
          <li><a href="/a/${_id}">0 comments</a></li>
          {{/if}}
          <li><a href="${source_url}" target="_blank">View Original</a></li>
          <li><a href="/s/${source_slug}">Stream for ${name}</a></li>
        </ul>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </article>
  </script>

  <% if @activity %>
  <script id="commentsTemplate" type="text/x-jquery-tmpl">
    <div id="comment">
      {{if !signedIn}}
        <h4>To leave a comment, please <a href="/auth">sign in</a>.</h4>
      {{else}}
      <h4>Leave a comment (as ${userName})</h4>
      <%= form_tag(comment_url(@activity.id), :method => :post) %>
      <ul>
        <li>
          <label>&nbsp;</label>
          <textarea id="id_description" class="textarea" name="body"></textarea>
        </li>
        <li class="clear">
          <button class="postBtn" type="submit">
            <span>Post</span>
          </button>
        </li>
      </ul>
      </form>
      {{/if}}
    </div>
    <div class="clear"></div>
    {{if comments}}
    <h4 id="commentTitle">Comments</h4>
    <ol id="comments">

    {{each comments}}
    <li>
      <span class="postNumber">${$index+1}</span>
      <div class="postContent">
        <a class="commenterName">${$value.display_name}</a>
        <div class="commentMetaData">
          <span>${$.format.date(new Date(lamestamp($value.created_at)), "MM.dd.yyyy")}</span>
          <span>${$.format.date(new Date(lamestamp($value.created_at)), "hh:mm a")}</span>
        </div>
        <p>${$value.body}</p>
      </div>
      <div class="clear"></div>
    </li>
    {{/each}}
    </ol>
    {{/if}}
  </script>
  <% end %>

  <script type="text/javascript">
  var _sf_async_config={uid:14977,domain:"streamcongress.com"};
  (function(){
    function loadChartbeat() {
      window._sf_endpt=(new Date()).getTime();
      var e = document.createElement('script');
      e.setAttribute('language', 'javascript');
      e.setAttribute('type', 'text/javascript');
      e.setAttribute('src',
         (("https:" == document.location.protocol) ? "https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/" : "http://static.chartbeat.com/") +
         "js/chartbeat.js");
      document.body.appendChild(e);
    }
    var oldonload = window.onload;
    window.onload = (typeof window.onload != 'function') ?
       loadChartbeat : function() { oldonload(); loadChartbeat(); };
  })();

  </script>

  <%= javascript_include_tag 'eventsource.polyfill', 'jquery.autocomplete.min', 'jquery.dateFormat', 'store', 'application', 'geolocation', 'underscore.min' %>
</body>
</html>